POST https://bootcamp-api.codeit.kr/api/sign-in/
Content-Type: application/json

{
  "email":"test@codeit.com",
  "password":"sprint101"
}

###
GET https://bootcamp-api.codeit.kr/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IktLNE05TGFmMXkzWEI0M0kiLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzEzMzIyNTY4LCJpYXQiOjE3MTI3MTc3NjgsImlzcyI6Imh0dHBzOi8vanB2ZG9weWdibHJlZnpvbmV2ZnEuc3VwYWJhc2UuY28vYXV0aC92MSIsInN1YiI6Ijk1NTgwMWE4LTg1YzUtNDY3Mi1iNzI5LTYxMmU2NDZhNjQwYSIsImVtYWlsIjoidGVzdEBjb2RlaXQuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6e30sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3MTI3MTc3Njh9XSwic2Vzc2lvbl9pZCI6IjllMjhjYzcwLWJhOWEtNDEwNy05NTgzLTIyOWE0YjAzMmNmNCIsImlzX2Fub255bW91cyI6ZmFsc2V9.KXkTIv-wMKgDJwHH7_SNjunRQ-lV_TYc8wMLW8SVqLs
###
GET https://bootcamp-api.codeit.kr/api/folders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IktLNE05TGFmMXkzWEI0M0kiLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzEzMzIyNTY4LCJpYXQiOjE3MTI3MTc3NjgsImlzcyI6Imh0dHBzOi8vanB2ZG9weWdibHJlZnpvbmV2ZnEuc3VwYWJhc2UuY28vYXV0aC92MSIsInN1YiI6Ijk1NTgwMWE4LTg1YzUtNDY3Mi1iNzI5LTYxMmU2NDZhNjQwYSIsImVtYWlsIjoidGVzdEBjb2RlaXQuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6e30sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3MTI3MTc3Njh9XSwic2Vzc2lvbl9pZCI6IjllMjhjYzcwLWJhOWEtNDEwNy05NTgzLTIyOWE0YjAzMmNmNCIsImlzX2Fub255bW91cyI6ZmFsc2V9.KXkTIv-wMKgDJwHH7_SNjunRQ-lV_TYc8wMLW8SVqLs
###
GET https://bootcamp-api.codeit.kr/api/links
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IktLNE05TGFmMXkzWEI0M0kiLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzEzMzIyNTY4LCJpYXQiOjE3MTI3MTc3NjgsImlzcyI6Imh0dHBzOi8vanB2ZG9weWdibHJlZnpvbmV2ZnEuc3VwYWJhc2UuY28vYXV0aC92MSIsInN1YiI6Ijk1NTgwMWE4LTg1YzUtNDY3Mi1iNzI5LTYxMmU2NDZhNjQwYSIsImVtYWlsIjoidGVzdEBjb2RlaXQuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6e30sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3MTI3MTc3Njh9XSwic2Vzc2lvbl9pZCI6IjllMjhjYzcwLWJhOWEtNDEwNy05NTgzLTIyOWE0YjAzMmNmNCIsImlzX2Fub255bW91cyI6ZmFsc2V9.KXkTIv-wMKgDJwHH7_SNjunRQ-lV_TYc8wMLW8SVqLs
###
GET https://bootcamp-api.codeit.kr/api/links?folderId=282
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IktLNE05TGFmMXkzWEI0M0kiLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzEzMzIyNTY4LCJpYXQiOjE3MTI3MTc3NjgsImlzcyI6Imh0dHBzOi8vanB2ZG9weWdibHJlZnpvbmV2ZnEuc3VwYWJhc2UuY28vYXV0aC92MSIsInN1YiI6Ijk1NTgwMWE4LTg1YzUtNDY3Mi1iNzI5LTYxMmU2NDZhNjQwYSIsImVtYWlsIjoidGVzdEBjb2RlaXQuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6e30sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3MTI3MTc3Njh9XSwic2Vzc2lvbl9pZCI6IjllMjhjYzcwLWJhOWEtNDEwNy05NTgzLTIyOWE0YjAzMmNmNCIsImlzX2Fub255bW91cyI6ZmFsc2V9.KXkTIv-wMKgDJwHH7_SNjunRQ-lV_TYc8wMLW8SVqLs
###
GET https://bootcamp-api.codeit.kr/api/users/1/folders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IktLNE05TGFmMXkzWEI0M0kiLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzEzMzIyNTY4LCJpYXQiOjE3MTI3MTc3NjgsImlzcyI6Imh0dHBzOi8vanB2ZG9weWdibHJlZnpvbmV2ZnEuc3VwYWJhc2UuY28vYXV0aC92MSIsInN1YiI6Ijk1NTgwMWE4LTg1YzUtNDY3Mi1iNzI5LTYxMmU2NDZhNjQwYSIsImVtYWlsIjoidGVzdEBjb2RlaXQuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6e30sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3MTI3MTc3Njh9XSwic2Vzc2lvbl9pZCI6IjllMjhjYzcwLWJhOWEtNDEwNy05NTgzLTIyOWE0YjAzMmNmNCIsImlzX2Fub255bW91cyI6ZmFsc2V9.KXkTIv-wMKgDJwHH7_SNjunRQ-lV_TYc8wMLW8SVqLs